apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar2-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar2
  template:
    metadata:
      labels:
        app: hotstar2
    spec:
      containers:
      - name: hotstar
        image: stephen0994/hotstar2:latest
        ports:
        - containerPort: 3002  # Port your application listens on
