apiVersion: v1
kind: Service
metadata:
  name: hotstar2-service
spec:
  selector:
    app: hotstar2
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service externally (outside the cluster)
      targetPort: 3002 # Port your application listens on inside the pods
  type: LoadBalancer
